server:
  port: 8080
  servlet:
    context-path: /
# ?????
alipay:
  # ??ID
  appId: 9021000150661092
  # ?????????????????
  privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCMLpH80VKJXJAnDHbeWgBNakKUFkzfEQdqFvlQSRJZq7Ngb2bLMx8GFteW+/AqwaZiqZ0KBTdc1al0HDbwjeOHGHnHicF5p2a78HZ2gZkSSHSx5KXE2aVUJX38bRxgEXYglIaFPRGGAnMmaOdSC0f21a+r8yKJv7+84swS9mAK5Vxy3PeBXR42mI5MRyqUxjTfO2+AzMTzzPGgyh44Go6xf8UlPStSjcahaOj0Fr8cr1NJCLUeb011y4R83wNvcSJ3LT0tsjxhUdNpAuLLWg5pCEEOL022czSWr7uO35Ywbl7UFhE2sTbcIBlOug7V7gm9ZKweEJEWvx7Vpq4YEFW1AgMBAAECggEAXETXAKLDAfj0RU+V+jshUdNsaU7YYEc0KydeCPNf6bfzhLku3vcSJ47nbtD7vxjhrLVZ0VunmipktDFSFDpAlg6NMcLBn5KJM5FOWChrmbYpYWJPnmdnxCA9ceZbs/wqVb2NYavVmfCI3LJV+BHG13jFfZe2lxaoXOqnSp/yjZh6TMvN0xYjFUIIktqhVyzGFrbluN5zcxvmLLoU5NeSZvf7nz8CQ4H7mPtU3Ch5Whrj5tqX7JVyVLo4aG0D6nC41kct+ZVItKp96Neip3e1VWWI6vMlbMSp6VOQfAPi+YTOpi8nLHMlMquALZMuDFLA2mHhdzqRc3jCbGC13o/UTQKBgQDO4PTUkmyNRJPWLjrO/Dc/REIuBr92hGiHIl/RaiFPgzrRPqRz103xHPS1uLA0WbvmrDY6k1KjkNjOR6ogygqJzjapgjVw9EioqjULTrfKuY5RpovzOZLd7MeDm/ua2jesg12kQb0f/wZiV9S9Q/l6gyqGGhfTm3jylYjPoKR7hwKBgQCtd3k6MpOL7CFxjk47AR5/Xil+0WbsL1CEAkAbfp6cyJ6b3yyxRVOHwb2hL16CcBQ2eRG/oftMySEjHYyAX2eP4HgfDQPMdvsiW5eq/qP7DS8iRGp99ZRIaK1j4o5vU2PdF4GcmJj+3wr32kn6L7cnQLcYl0GAAUaTuBPWjdgL4wKBgH9FSZmU0w89hy2WlztLUrmrRoOGRzekUaIA9a2hewitlPuxa/6QEDUrOSiqjExIgB5zB5GVnJtfuuF8mR8+7KjGoj46CqKIxkJtI+Dm9o7TBMkairKBUucQidVfmrQzV1jcIDmy76TFganymsAtF0fVdc22M75MwWWLtPT2wPn1AoGAcyt3mWQrAiNssPBCkHpVvUrPUhvFsdpYIs07swWGWaH5bJPoIGpe4yuGs5W3sfKn+OK5Hfp11q1TCvV7a1/samImXrdNZls4sb8OG8GlLfG68Y1rBuYd5VVaiY7J8q/zBb+tlkLakZ2UsqqDo1A60hztc645FrvCGCGHSlQytPECgYAfxSTnVR2zAB2ez/DhvKSkrGWSplJ+1nF/bR3R3NReYNmGbSwRJutvZO+UHEDzNo5oXLpbRPrVv4xHKRMBG6VB1yeCLavi8VYROWotYSP2QYeYbLiQ7L1+aQHCwQxpjXfMMQl53J+dudYBtK3fzBk2jVzXdpZSLQWpa3pLYqKDSQ==
  # ??????????????????
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwhYSKaRIFnV2ByEic38Qiqyz9XvA3p1Ky4c6EQmQ6F8xOGJHZ7Xixx4LM10MftsWT0oNNPWaLDZp43Lo9IDaHmx/8bpxoaSOCxOSQ6Y97bkDNoIUwjpJUa89Jn1DlPJ1A78MJTuoCXhjRo3iUKyMGM6MS07OpBKbQVwFaxIkXqr9tK1KY8gnxSOKNsQ0OT8rQLNnQNw1H+hGMPjw5panJEwPdMHDZPC6MUgSB7PsDLZcDKQih/aJxgEGJOChwKiMFxVHy1pnyqcZmuMEZ3ts9Vi4jfCE8CP3zYtx3DDQ3yYMXi9G4SsujatO3v77aQ8uO29DmaM7VKa8bwpoLVLlmwIDAQAB
  # ????????????????????
  notifyUrl: http://localhost:8080/alipay/notify
  # ????????????
  returnUrl: http://localhost:8080/alipay/return
  # ????
  signType: RSA2
  # ??????
  charset: UTF-8
  # ???????????
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  # ??
  format: JSON

spring:
  application:
    name: phoneshop
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/phoneshop?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  # Thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 587
    username: 2862857996@qq.com  # 请替换为实际的邮箱
    password: kynshzeknmnldhdh      # 请替换为实际的密码或授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000

  # Session配置
  session:
    store-type: none
    timeout: 30m

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.duoduo.phoneshop.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    com.duoduo.phoneshop: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/phoneshop.log

# 自定义配置
app:
  name: 多多购手机网站
  version: 1.0.0
  upload-path: ./upload/